config/routes.rb
Rails.application.routes.draw do
  
  root 'mainpage#index'
  get '/home', to: 'mainpage#index'
  
  #get '/recipes', to: 'recipes#index'
  #et 'recipes/new', to: 'recipes#index', as: 'new_recipe'
  #post '/recipes', to: 'recipes#create'
  #get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  #patch '/recipes/:id', to: 'recipes#update'
  #get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  #delete 'recipes/:id', to: 'recipes#destroy'

  resources :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :name, presence: true, length: {minimum: 3, maximum: 20}
  validates :summary, presence: true, length: {minimum: 30, maximum: 250}
  validates :directions, presence: true, length: {minimum: 50, maximum: 350}
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes
  validates :firstName, presence: true, length: { minimum: 3, maximum: 12 }
  validates :lastName, presence: true, length: { minimum: 2, maximum: 18 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save { self.email = email.downcase }
  validates :email, presence:true, length: { maximum: 54 },uniqueness: { case_sensitive: false },
format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mainpage_controller.rb
class MainpageController < ApplicationController
    def index
      
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  
  def show
    @recipe = Recipe.find(params[:id])
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = User.find(1)
    
    if @recipe.save
      flash[:success] = "Your recipe was created"
    redirect_to recipes_path
    else
      render :new
    end
  end
  
  def edit
    @recipe = Recipe.find(params[:id])
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      #do something
      flash[:success] = "Your recipe is updated successfully"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end
private

  def recipe_params
    params.require(:recipe).permit(:name, :summary, :directions)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

def gravtar_for(user, options = { size: 80 })
  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  size = options[:size]
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url, alt: user.firstName, class: "gravatar")
end

end

app/helpers/mainpage_helper.rb
module MainpageHelper
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Coffeelecious</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search here">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-lrft">
        <li><%= link_to "new recipe", new_recipe_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href = "#">Login</a></li>
        <li><a href ="#">Signup</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffeelecious</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>

app/views/mainpage/index.html.erb
<div class = "container">
    <div class="welcome_header">Welcome to Coffeelecious</div>
    <div class="welcome_content">
        Welcome to this community of coffee lovers.<br />
        Here you can enjoy and post new coffee recipies.
    </div>
    <hr />
<div class = "top_10_picks">
    <div class="top_10_picks_header">
        These are top 10 voted coffee drinks.
    </div>
</div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>


    <%= form_for @recipe do |f| %> 
<%= f.label :name %> 
<%= f.text_field :name %> 
 <br />
<%= f.label :summary %> 
<%= f.text_field :summary %> 
 <br />
<%= f.label :directions %> 
<%=f.text_area :directions %> 
 <br />
<%= f.submit(@recipe.new_record? ? 'create recipe' : 'edit recipe', class: "btn btn-success") %> 
<% end %>

app/views/recipes/edit.html.erb
<p>
    <center><h1>Edit your existing recipe</h1></center>
</p>

<%= render 'form' %>

app/views/recipes/index.html.erb
<center><h1>All Recipes</h1></center>
<hr />

<% @recipes.each do |recipe| %>
    <div class = "row">
        <div class="col-md-2">
           <section class="chef_info center">
               <%= gravtar_for recipe.user, size: 100 %>
               <h5>Name<br /><%= recipe.user.firstName %>&nbsp;<%= recipe.user.lastName %></h5>
           </section> 
        </div>
        
        <div class="col-lg-8 well">
            <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
        <p><%= recipe.summary %></p>
        <p>
            <span class= "quiet"><small> <%= time_ago_in_words(recipe.created_at) %></small></span>
        </p>
        </div>
        
    </div>
<% end %>

app/views/recipes/new.html.erb
<p>
    <center><h1>Create a new recipe</h1></center>
</p>

<%= render 'form' %>

app/views/recipes/show.html.erb
<center><h2><%= @recipe.name %></h2>
<%= gravtar_for @recipe.user, size: 150, class: "gravatar_at_userid"  %><br />
<small>Written By:<%= @recipe.user.firstName+ " "+@recipe.user.lastName %></small>
</center>
<%= link_to "Edit your recipe", edit_recipe_path(@recipe) %>
<p>
    <h3>Summary:</h3>
    <%= @recipe.summary %>
</p>
<p>
    <h3>Directions:</h3>
    <%= simple_format(@recipe.directions) %>
</p>

<%= link_to 'back to index page', '/recipes' %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  </div>
<% end %>